<?php

namespace App\Http\Controllers;

use App\Models\Property;
use App\Models\District;
use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Inertia\Inertia;

class PropertyController extends Controller
{
    public function index()
    {
        return Inertia::render('properties/properties-index', [
            'properties' => Property::with(['user', 'district.region'])->orderBy('description')->get(),
        ]);
    }

    public function create()
    {
        return Inertia::render('properties/properties-create', [
            'typeOptions' => [
                'casa' => 'Casa',
                'casa (condom.)' => 'Casa (Condom.)',
                'sobrado' => 'Sobrado',
                'apartamento' => 'Apartamento',
                'apart. c/ elevad.' => 'Apart. c/ Elevad.',
                'terreno' => 'Terreno',
                'loja' => 'Loja',
                'garagem' => 'Garagem',
                'sala' => 'Sala',
                'outros' => 'Outros',
            ],
            'airConditioningOptions' => [
                'incluso' => 'Incluso',
                'somente infra' => 'Somente Infraestrutura',
                'não incluso' => 'Não Incluso',
            ],
            'booleanOptions' => [
                'true' => 'Sim',
                'false' => 'Não',
            ],
            'districtOptions' => District::orderBy('name')->get()->pluck('name', 'id'),
        ]);
    }

    public function store(Request $request): RedirectResponse
    {
        // In your seeder or migration file
        $properties = [
            [
                'description' => 'Pátio SP - Planeta',
                'price' => 450000,
                'land_area' => 69,
                'rooms' => 2,
                'suites' => 1,
                'garages' => 1,
                'building_floors' => 19,
                'delivery_key' => '2026-06-15',
                'min_act' => 5,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Personalize',
                'garden' => true,
                'obs' => 'Alto padrão',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Pátio SP - Planeta',
                'price' => 600000,
                'land_area' => 80,
                'rooms' => 2,
                'suites' => 1,
                'garages' => 2,
                'building_floors' => null,
                'delivery_key' => '2026-07-15',
                'min_act' => null,
                'installment_payment' => false,
                'documents' => false,
                'finsh_type' => null,
                'garden' => false,
                'obs' => null,
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Residencial Luíza',
                'price' => 222000,
                'land_area' => 45.45,
                'rooms' => 2,
                'suites' => 0,
                'garages' => 1,
                'building_floors' => null,
                'delivery_key' => '2025-03-15',
                'min_act' => null,
                'installment_payment' => false,
                'documents' => false,
                'finsh_type' => null,
                'garden' => false,
                'obs' => null,
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Bella Veneza',
                'price' => 189996.75,
                'land_area' => 40.49,
                'rooms' => 2,
                'suites' => null,
                'garages' => 1,
                'building_floors' => 14,
                'delivery_key' => '2026-03-15',
                'min_act' => 5,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Padrão',
                'garden' => true,
                'obs' => 'Preço já com desconto bom pagador de 10 mil.\r\nAs Torres serão entregues a partir de setembro de 2025, da 1° para a Última ',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Mirage São Paulo',
                'price' => 217200,
                'land_area' => 44,
                'rooms' => 2,
                'suites' => 0,
                'garages' => 1,
                'building_floors' => 21,
                'delivery_key' => '2026-12-15',
                'min_act' => 5,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Padrão',
                'garden' => true,
                'obs' => null,
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Mirage São Paulo',
                'price' => 245000,
                'land_area' => 45,
                'rooms' => 2,
                'suites' => 0,
                'garages' => 1,
                'building_floors' => null,
                'delivery_key' => '2026-03-15',
                'min_act' => null,
                'installment_payment' => false,
                'documents' => false,
                'finsh_type' => null,
                'garden' => false,
                'obs' => null,
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Íris Residence',
                'price' => 250400,
                'land_area' => 50.87,
                'rooms' => 2,
                'suites' => 1,
                'garages' => 1,
                'building_floors' => 17,
                'delivery_key' => '2025-07-15',
                'min_act' => 1,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Opção laminado',
                'garden' => true,
                'obs' => 'Opção com 2 vagas de garagem',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Pq dos ingl. - Londres',
                'price' => 450000,
                'land_area' => 69,
                'rooms' => 3,
                'suites' => 1,
                'garages' => 2,
                'building_floors' => null,
                'delivery_key' => '2025-07-15',
                'min_act' => null,
                'installment_payment' => false,
                'documents' => false,
                'finsh_type' => null,
                'garden' => false,
                'obs' => null,
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Siver Oásis',
                'price' => 222700,
                'land_area' => 47,
                'rooms' => 2,
                'suites' => 0,
                'garages' => 1,
                'building_floors' => 10,
                'delivery_key' => '2025-07-15',
                'min_act' => 5,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Padrão',
                'garden' => true,
                'obs' => 'Rua Ritinha Tavares, 140\r\n2 Torres, sendo térreo+ 10 andares\r\n\r\n',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Vale Verde Barcelona',
                'price' => 245000,
                'land_area' => 49,
                'rooms' => 2,
                'suites' => 0,
                'garages' => 1,
                'building_floors' => null,
                'delivery_key' => '2023-12-15',
                'min_act' => null,
                'installment_payment' => false,
                'documents' => false,
                'finsh_type' => null,
                'garden' => false,
                'obs' => null,
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'V.V. Wan. Ville',
                'price' => 248000,
                'land_area' => 49.55,
                'rooms' => 2,
                'suites' => 0,
                'garages' => 1,
                'building_floors' => null,
                'delivery_key' => '2023-12-15',
                'min_act' => null,
                'installment_payment' => false,
                'documents' => false,
                'finsh_type' => null,
                'garden' => false,
                'obs' => null,
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Sky Life - L. Furtado',
                'price' => 260000,
                'land_area' => 48,
                'rooms' => 2,
                'suites' => 0,
                'garages' => 1,
                'building_floors' => null,
                'delivery_key' => '2024-01-15',
                'min_act' => null,
                'installment_payment' => false,
                'documents' => false,
                'finsh_type' => null,
                'garden' => false,
                'obs' => null,
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Sun Lake - MRV',
                'price' => 234990,
                'land_area' => 46.77,
                'rooms' => 2,
                'suites' => 0,
                'garages' => 1,
                'building_floors' => 0,
                'delivery_key' => '2024-01-15',
                'min_act' => 2,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Porcelanato',
                'garden' => true,
                'obs' => null,
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Cozumel ES Const.',
                'price' => 194490,
                'land_area' => 45,
                'rooms' => 2,
                'suites' => 0,
                'garages' => 1,
                'building_floors' => 9,
                'delivery_key' => '2025-12-15',
                'min_act' => 4,
                'installment_payment' => true,
                'documents' => false,
                'finsh_type' => null,
                'garden' => true,
                'obs' => 'Torre única, opção com vaga coberta.\r\n\r\nApartamento entregue',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],

            [
                'description' => 'Res. Parque Viena',
                'price' => 314620,
                'land_area' => 67.45,
                'rooms' => 3,
                'suites' => 1,
                'garages' => 1,
                'building_floors' => null,
                'delivery_key' => '2023-12-15',
                'min_act' => null,
                'installment_payment' => false,
                'documents' => false,
                'finsh_type' => null,
                'garden' => false,
                'obs' => null,
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Residencial Luiza',
                'price' => 325000,
                'land_area' => 68.91,
                'rooms' => 3,
                'suites' => 1,
                'garages' => 1,
                'building_floors' => null,
                'delivery_key' => '2025-03-15',
                'min_act' => null,
                'installment_payment' => false,
                'documents' => false,
                'finsh_type' => null,
                'garden' => false,
                'obs' => null,
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Res. Daniel Gonzales',
                'price' => 223200,
                'land_area' => 46,
                'rooms' => 2,
                'suites' => 0,
                'garages' => 1,
                'building_floors' => 18,
                'delivery_key' => '2026-12-15',
                'min_act' => 5,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Padrão',
                'garden' => true,
                'obs' => null,
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Res. Daniel Gonzales',
                'price' => 256800,
                'land_area' => 50,
                'rooms' => 2,
                'suites' => 1,
                'garages' => 1,
                'building_floors' => 18,
                'delivery_key' => '2026-12-15',
                'min_act' => 5,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Padrão',
                'garden' => true,
                'obs' => null,
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Lar Roma',
                'price' => 197900,
                'land_area' => 41,
                'rooms' => 2,
                'suites' => 0,
                'garages' => 1,
                'building_floors' => 3,
                'delivery_key' => '2025-10-15',
                'min_act' => 1,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Laminado',
                'garden' => false,
                'obs' => 'Correção pós Chaves ipca 1 por cento',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Bella Veneza Suite',
                'price' => 211690,
                'land_area' => 45.87,
                'rooms' => 2,
                'suites' => 1,
                'garages' => 1,
                'building_floors' => 14,
                'delivery_key' => '2025-10-15',
                'min_act' => 5,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Padrão',
                'garden' => true,
                'obs' => 'Preço já com desconto bom pagador de 10mil',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'IpaClub Residencial',
                'price' => 320000,
                'land_area' => 53,
                'rooms' => 2,
                'suites' => 1,
                'garages' => 1,
                'building_floors' => 22,
                'delivery_key' => '2026-08-15',
                'min_act' => 5,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Padrão',
                'garden' => true,
                'obs' => 'Unidades de 1 dormitório a partir de 260 mil tab de setembro/23.\r\n\r\nEntregue com cerâmica Áreas molhadas e laminado nas secas.',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Parc Ipe Vermelho',
                'price' => 226900,
                'land_area' => 49,
                'rooms' => 2,
                'suites' => 0,
                'garages' => 1,
                'building_floors' => 14,
                'delivery_key' => '2025-07-15',
                'min_act' => 5,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Laminado',
                'garden' => true,
                'obs' => 'Lazer na cobertura',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Trion',
                'price' => 549400,
                'land_area' => 69.03,
                'rooms' => 2,
                'suites' => 2,
                'garages' => 2,
                'building_floors' => 24,
                'delivery_key' => '2026-10-15',
                'min_act' => 8,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Top',
                'garden' => false,
                'obs' => 'Torre única na rua Capitão Grandino, 445 Jd Paulistano',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Atmo',
                'price' => 554400,
                'land_area' => 67.75,
                'rooms' => 2,
                'suites' => 1,
                'garages' => 2,
                'building_floors' => 19,
                'delivery_key' => '2024-10-15',
                'min_act' => 8,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Top',
                'garden' => false,
                'obs' => 'Torre Topro, 89 e 115 m\r\nTorre Meso,67 e 96m\r\nO financiamento se inicia nas chaves.',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],

            [
                'description' => 'JR Buena V. Clube',
                'price' => 292937.77,
                'land_area' => 60.15,
                'rooms' => 2,
                'suites' => 1,
                'garages' => 1,
                'building_floors' => 21,
                'delivery_key' => '2026-08-15',
                'min_act' => 5,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Laminado nas áreas secas',
                'garden' => true,
                'obs' => '3 elevadores por torre\r\nBloco B, 3 dormitórios, final 2 e 3\r\nEntregue com fechadura eletrônica',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'JJR Hortência',
                'price' => 267968.29,
                'land_area' => 53.75,
                'rooms' => 2,
                'suites' => 1,
                'garages' => 1,
                'building_floors' => 24,
                'delivery_key' => '2024-12-15',
                'min_act' => 5,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Laminado nas áreas secas',
                'garden' => true,
                'obs' => null,
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Vale verde horto',
                'price' => 299999.99,
                'land_area' => null,
                'rooms' => 2,
                'suites' => 0,
                'garages' => 1,
                'building_floors' => 17,
                'delivery_key' => '2023-07-15',
                'min_act' => null,
                'installment_payment' => true,
                'documents' => false,
                'finsh_type' => 'Padão',
                'garden' => false,
                'obs' => null,
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Park Ville Residencial',
                'price' => 212458.2,
                'land_area' => 47.61,
                'rooms' => 2,
                'suites' => 1,
                'garages' => 1,
                'building_floors' => 11,
                'delivery_key' => '2026-07-15',
                'min_act' => 5,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Padão',
                'garden' => true,
                'obs' => 'Duplex no 11º andar\r\n51 vagas de moto\r\n3 Torres',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'JR Campolim 2',
                'price' => 304238.44,
                'land_area' => 60,
                'rooms' => 2,
                'suites' => 1,
                'garages' => 1,
                'building_floors' => 20,
                'delivery_key' => '2024-10-15',
                'min_act' => 5,
                'installment_payment' => true,
                'documents' => false,
                'finsh_type' => 'Laminado',
                'garden' => false,
                'obs' => null,
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Gran Vic Astúrias',
                'price' => 260000,
                'land_area' => 49,
                'rooms' => 2,
                'suites' => 0,
                'garages' => 1,
                'building_floors' => 17,
                'delivery_key' => '2024-05-15',
                'min_act' => 1,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Padrão',
                'garden' => false,
                'obs' => 'Rua Comendador Vicente Amaral, 2088',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Vila Zamora',
                'price' => 264400,
                'land_area' => 55.1,
                'rooms' => 2,
                'suites' => 1,
                'garages' => 1,
                'building_floors' => 16,
                'delivery_key' => '2024-10-15',
                'min_act' => 2,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Dorm Laminado, resto ceramica',
                'garden' => true,
                'obs' => '2 torres, garden +16, 2 elevadores por torre; play com piso emborrachado, área de lazer climatizada.',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Vila Laredo',
                'price' => 254300,
                'land_area' => 49.74,
                'rooms' => 2,
                'suites' => 1,
                'garages' => 1,
                'building_floors' => 16,
                'delivery_key' => '2025-09-15',
                'min_act' => 5,
                'installment_payment' => true,
                'documents' => false,
                'finsh_type' => 'Cerâmica+Laminado nos dorm.',
                'garden' => true,
                'obs' => '2 Torres, térreo+16 na A,+15 na B.\r\nAptos 49,74/51,18/55,90. Opç garden e suites, até 2 vagas.\r\nCerâmica na sala, Laminado dorm.\r\nPonto ar apenas Dormitórios',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Real Parque',
                'price' => 500000,
                'land_area' => 36,
                'rooms' => 3,
                'suites' => 1,
                'garages' => null,
                'building_floors' => null,
                'delivery_key' => '2024-12-15',
                'min_act' => null,
                'installment_payment' => false,
                'documents' => false,
                'finsh_type' => null,
                'garden' => false,
                'obs' => null,
                'user_id' => 12,
                'district_id' => 2, // Note different district_id
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Bella Vista',
                'price' => 200500,
                'land_area' => 56,
                'rooms' => 3,
                'suites' => 2,
                'garages' => null,
                'building_floors' => 8,
                'delivery_key' => '2024-07-15',
                'min_act' => null,
                'installment_payment' => false,
                'documents' => false,
                'finsh_type' => null,
                'garden' => false,
                'obs' => null,
                'user_id' => 12,
                'district_id' => 2, // Note different district_id
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Lituânia',
                'price' => 295000,
                'land_area' => 57.21,
                'rooms' => 2,
                'suites' => 1,
                'garages' => 1,
                'building_floors' => 11,
                'delivery_key' => '2026-07-15',
                'min_act' => 10,
                'installment_payment' => true,
                'documents' => false,
                'finsh_type' => 'Laminado nos quartos',
                'garden' => true,
                'obs' => 'Preparação para chuveiro a gás',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Vila dos Sonhos',
                'price' => 400000,
                'land_area' => 56,
                'rooms' => 2,
                'suites' => 1,
                'garages' => 1,
                'building_floors' => 12,
                'delivery_key' => '2025-11-15',
                'min_act' => 5,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Azulejo',
                'garden' => true,
                'obs' => 'Muito bem localizado.',
                'user_id' => 12,
                'district_id' => 2, // Note different district_id
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'In Resid Clube',
                'price' => 200018.95,
                'land_area' => 44.37,
                'rooms' => 2,
                'suites' => 0,
                'garages' => 1,
                'building_floors' => 20,
                'delivery_key' => '2026-02-15',
                'min_act' => 5,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Cerâmica completo',
                'garden' => true,
                'obs' => 'Planta de 44.37 m ventil. mecânica\r\n2 Torres, 2 elev por torre\r\nVaga descoberta',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],

            [
                'description' => 'Unitá',
                'price' => 303641.24,
                'land_area' => 50.48,
                'rooms' => 2,
                'suites' => 1,
                'garages' => 1,
                'building_floors' => 17,
                'delivery_key' => '2024-06-15',
                'min_act' => 5,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Completo porcelanato',
                'garden' => false,
                'obs' => 'Estacionamento no subsolo e térreo com área de lazer\r\nSalão de festas, play, Coworking, petwash, academia , sem piscina.',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Lisieux',
                'price' => 365511.94,
                'land_area' => 57.64,
                'rooms' => 2,
                'suites' => 1,
                'garages' => 1,
                'building_floors' => 19,
                'delivery_key' => '2026-01-15',
                'min_act' => 5,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Completo porcelanato',
                'garden' => false,
                'obs' => 'Torre única, subsolo e térreo com garagem e área lazer, sem piscina, todas com suíte. Varanda pode integrar a sala.',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Bella Veneza',
                'price' => 450000,
                'land_area' => 50,
                'rooms' => 3,
                'suites' => 1,
                'garages' => 1,
                'building_floors' => 15,
                'delivery_key' => '2024-08-15',
                'min_act' => 10,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Azulejo',
                'garden' => true,
                'obs' => 'Preço com desconto',
                'user_id' => 12,
                'district_id' => 2, // Different district_id for user_id = 2
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Parque Vida',
                'price' => 232000,
                'land_area' => 52,
                'rooms' => 2,
                'suites' => 0,
                'garages' => 1,
                'building_floors' => 19,
                'delivery_key' => '2026-09-15',
                'min_act' => 2,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Cerâmica+laminado',
                'garden' => true,
                'obs' => 'Produto planeta, 4 apês por andar, 2 elevadores por torre. 50% de vagas cobertas já demarcada.\r\nÁrea de lazer equipada',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Dáhlia',
                'price' => 280000,
                'land_area' => 58,
                'rooms' => 2,
                'suites' => 1,
                'garages' => 2,
                'building_floors' => 9,
                'delivery_key' => '2025-12-15',
                'min_act' => 5,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Porcelanato',
                'garden' => false,
                'obs' => 'Torre única, 2 elevadores, vagas no subsolo e lazer no terraço\r\nAptos final 3 e 4 com suite, sol da manhã; final 1 e 3 sem suite, sol da tarde',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Seattle',
                'price' => 229900,
                'land_area' => 51,
                'rooms' => 2,
                'suites' => 0,
                'garages' => 1,
                'building_floors' => 9,
                'delivery_key' => '2027-01-15',
                'min_act' => 5,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Padrão',
                'garden' => false,
                'obs' => 'Lançamento, em fase de demanda \r\nEndereço: Av Luiz Mendes de Almeida, 1880',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Residencial Shrek',
                'price' => 234000,
                'land_area' => 23,
                'rooms' => 1,
                'suites' => 1,
                'garages' => 0,
                'building_floors' => 1,
                'delivery_key' => '2026-06-15',
                'min_act' => 3,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Lama',
                'garden' => true,
                'obs' => 'É incrível o que você fez com um orçamento tão modesto',
                'user_id' => 12,
                'district_id' => 2, // Different district_id for user_id = 2
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Amarílis',
                'price' => 323900,
                'land_area' => 61,
                'rooms' => 2,
                'suites' => 1,
                'garages' => 1,
                'building_floors' => 18,
                'delivery_key' => '2025-07-15',
                'min_act' => 5,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Completo',
                'garden' => true,
                'obs' => 'Nada ainda',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Authentic',
                'price' => 600000,
                'land_area' => 106,
                'rooms' => 3,
                'suites' => 3,
                'garages' => null,
                'building_floors' => 20,
                'delivery_key' => '2026-01-15',
                'min_act' => 5,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Completo',
                'garden' => false,
                'obs' => 'Porcelanato + laminado nos quartos. Churrasqueira na varanda gourmet. Gerador de energia para tomada da geladeira, elevadores e um ponto na sala. Fechadura eletrônica. Opção personalize, com living ampliado.',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Flora Ibiti',
                'price' => 249144,
                'land_area' => 46,
                'rooms' => null,
                'suites' => 0,
                'garages' => null,
                'building_floors' => 15,
                'delivery_key' => '2024-09-15',
                'min_act' => 2,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Padrão',
                'garden' => false,
                'obs' => 'Tem casa Paulista',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Lar Dallas',
                'price' => 216000,
                'land_area' => 50,
                'rooms' => null,
                'suites' => 0,
                'garages' => null,
                'building_floors' => 0,
                'delivery_key' => '2026-02-15',
                'min_act' => 1,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Cerâmica+Laminado nos dorm.',
                'garden' => true,
                'obs' => 'Condomínio de casas, geminadas a cada 2 unidades, tamanho de quintal variado.',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'
            ],
            [
                'description' => 'Tropical',
                'price' => 1900000,
                'land_area' => 41.6,
                'rooms' => null,
                'suites' => null,
                'garages' => null,
                'building_floors' => null,
                'delivery_key' => '2026-04-15',
                'min_act' => null,
                'installment_payment' => true,
                'documents' => true,
                'finsh_type' => 'Padrão',
                'garden' => true,
                'obs' => 'Unidades com suíte e garden.',
                'user_id' => 12,
                'district_id' => 1,
                'type' => 'apartamento',
                'air_conditioning' => 'somente infra'

            ]

        ];

        foreach ($properties as $propertyData) {
            Property::create($propertyData);
        }


        return to_route('properties.index')->with('success', 'Property created successfully');


        $validated = $request->validate([
            'contact_name' => 'nullable|string',
            'contact_phone' => 'nullable|string',
            'contact_link' => 'nullable|string',
            'district_id' => 'required|integer|exists:districts,id',
            'type' => 'nullable|in:casa,casa (condom.),sobrado,apartamento,apart. c/ elevad.,terreno,loja,garagem,sala,outros',
            'iptu' => 'nullable|numeric|min:0',
            'description' => 'nullable|string',
            'price' => 'required|integer|min:0',
            'land_area' => 'nullable|numeric|min:0',
            'building_area' => 'nullable|numeric|min:0',
            'image' => 'nullable|string',
            'address' => 'nullable|string|max:100',
            'rooms' => 'nullable|integer|min:0',
            'bathrooms' => 'nullable|integer|min:0',
            'suites' => 'nullable|integer|min:0',
            'garages' => 'nullable|integer|min:0',
            'floor' => 'nullable|integer|min:0',
            'building_floors' => 'nullable|integer|min:0',
            'property_floors' => 'nullable|integer|min:0',
            'delivery_key' => 'nullable|date',
            'min_act' => 'nullable|integer|min:0',
            'installment_payment' => 'nullable|boolean',
            'incc_financing' => 'nullable|boolean',
            'documents' => 'nullable|boolean',
            'finsh_type' => 'nullable|string',
            'air_conditioning' => 'nullable|in:incluso,somente infra,não incluso',
            'garden' => 'nullable|boolean',
            'pool' => 'nullable|boolean',
            'balcony' => 'nullable|boolean',
            'acept_pets' => 'nullable|boolean',
            'acessibility' => 'nullable|boolean',
            'obs' => 'nullable|string',
        ]);

        $validated['user_id'] =  Auth::user()->id;

        $property = Property::create($validated);

        if ($property) {
            return to_route('properties.index')->with('success', 'Property created successfully');
        }

        return back()->with('error', 'Failed to create property');
    }

    public function show(Property $property)
    {
        return Inertia::render('properties/properties-show', [
            'property' => $property->load(['user', 'district']),
            'typeOptions' => [
                'casa' => 'Casa',
                'casa (condom.)' => 'Casa (Condom.)',
                'sobrado' => 'Sobrado',
                'apartamento' => 'Apartamento',
                'apart. c/ elevad.' => 'Apart. c/ Elevad.',
                'terreno' => 'Terreno',
                'loja' => 'Loja',
                'garagem' => 'Garagem',
                'sala' => 'Sala',
                'outros' => 'Outros',
            ],
            'airConditioningOptions' => [
                'incluso' => 'Incluso',
                'somente infra' => 'Somente Infraestrutura',
                'não incluso' => 'Não Incluso',
            ],
            'booleanOptions' => [
                'true' => 'Sim',
                'false' => 'Não',
            ],
        ]);
    }

    public function edit(Property $property)
    {
        return Inertia::render('properties/properties-edit', [
            'property' => $property,
            'typeOptions' => [
                'casa' => 'Casa',
                'casa (condom.)' => 'Casa (Cond.)',
                'sobrado' => 'Sobrado',
                'apartamento' => 'Apartamento',
                'apart. c/ elevad.' => 'Apart. c/ Elevad.',
                'terreno' => 'Terreno',
                'loja' => 'Loja',
                'garagem' => 'Garagem',
                'sala' => 'Sala',
                'outros' => 'Outros',
            ],
            'airConditioningOptions' => [
                'incluso' => 'Incluso',
                'somente infra' => 'Somente Infraestrutura',
                'não incluso' => 'Não Incluso',
            ],
            'booleanOptions' => [
                'true' => 'Sim',
                'false' => 'Não',
            ],
            'districtOptions' => District::orderBy('name')->get()->pluck('name', 'id'),
            'userOptions' => User::orderBy('name')->get()->pluck('name', 'id'),
        ]);
    }

    public function update(Request $request, Property $property): RedirectResponse
    {
        $validated = $request->validate([
            'contact_name' => 'nullable|string',
            'contact_phone' => 'nullable|string',
            'contact_link' => 'nullable|string',
            'district_id' => 'required|integer|exists:districts,id',
            'type' => 'nullable|in:casa,casa (condom.),sobrado,apartamento,apart. c/ elevad.,terreno,loja,garagem,sala,outros',
            'iptu' => 'nullable|numeric|min:0',
            'description' => 'nullable|string',
            'price' => 'required|integer|min:0',
            'land_area' => 'nullable|numeric|min:0',
            'building_area' => 'nullable|numeric|min:0',
            'image' => 'nullable|string',
            'address' => 'nullable|string|max:100',
            'rooms' => 'nullable|integer|min:0',
            'bathrooms' => 'nullable|integer|min:0',
            'suites' => 'nullable|integer|min:0',
            'garages' => 'nullable|integer|min:0',
            'floor' => 'nullable|integer|min:0',
            'building_floors' => 'nullable|integer|min:0',
            'property_floors' => 'nullable|integer|min:0',
            'delivery_key' => 'nullable|date',
            'min_act' => 'nullable|integer|min:0',
            'installment_payment' => 'nullable|boolean',
            'incc_financing' => 'nullable|boolean',
            'documents' => 'nullable|boolean',
            'finsh_type' => 'nullable|string',
            'air_conditioning' => 'nullable|in:incluso,somente infra,não incluso',
            'garden' => 'nullable|boolean',
            'pool' => 'nullable|boolean',
            'balcony' => 'nullable|boolean',
            'acept_pets' => 'nullable|boolean',
            'acessibility' => 'nullable|boolean',
            'obs' => 'nullable|string',
        ]);

        $validated['user_id'] =  Auth::user()->id;

        $property->update($validated);

        return back()->with('success', 'Property updated successfully');
    }

    public function destroy(Property $property): RedirectResponse
    {
        $property->delete();
        return to_route('properties.index')->with('success', 'Property deleted successfully');
    }
}
